favicon: /favicon.ico
rss: true

license:
  name: CC BY-NC-SA 4.0
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/

index_post_count: 5
tag_post_count: 3
read_cpm: 220

paths:
  tags: tags
  series: series

extra_header_links:
  GitHub Repo: https://github.com/outloudvi/hexo-theme-saas

features:
  hitokoto: false
  show_url_for_xs: true

# Don't change anything below

node_sass:
  debug: true
  includePaths:
    - node_modules
    - themes/saas/node_modules
