name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    if: "(!contains(github.event.commits[0].message, '[skip ci]')) && (!contains(github.event.commits[0].message, '[ci skip]'))"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout unit test
        uses: actions/checkout@v2
        with:
          repository: hexojs/hexo-theme-unit-test
          path: .

      - name: Checkout theme
        uses: actions/checkout@v2
        with:
          path: theme/landscape

      - name: Install and build
        run: |
          pwd
          ls -lahR
          npm install
          cd ../..
          pwd
          npm install
          ls -lah
          sudo npm install -g hexo-cli
          hexo generate

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: false
          BRANCH: gh-pages
          FOLDER: public
