name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    if: "(!contains(github.event.commits[0].message, '[skip ci]')) && (!contains(github.event.commits[0].message, '[ci skip]'))"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout unit test
        uses: actions/checkout@v2
        with:
          repository: hexojs/hexo-theme-unit-test
          path: "."
      
      - name: Checkout theme
        uses: actions/checkout@v2
        with:
          path: themes/saas

      - name: Install and build
        run: |
          pwd
          sed -i 's/url: http:\/\/yoursite.com/url: https:\/\/outloudvi.github.io\/hexo-theme-saas\//' _config.yml
          sed -i 's/root: \//root: \/hexo-theme-saas\//' _config.yml
          sed -i 's/theme: landscape/theme: saas/' _config.yml
          cat _config.yml
          npm install
          npm install hexo-renderer-sass bulma
          sudo npm install -g hexo-cli
          hexo generate
          ls -lah public/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: false
          BRANCH: gh-pages
          FOLDER: public
          SINGLE_COMMIT: true